// A comprehensive list of countries and their respective currencies.
// This ensures we have a fallback mapping for all major countries.

export const countries = [
  { code: 'AF', name: 'Afghanistan', nameAr: 'أفغانستان', currency: 'AFN' },
  { code: 'AL', name: 'Albania', nameAr: 'ألبانيا', currency: 'ALL' },
  { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر', currency: 'DZD' },
  { code: 'AD', name: 'Andorra', nameAr: 'أندورا', currency: 'EUR' },
  { code: 'AO', name: 'Angola', nameAr: 'أنغولا', currency: 'AOA' },
  { code: 'AR', name: 'Argentina', nameAr: 'الأرجنتين', currency: 'ARS' },
  { code: 'AM', name: 'Armenia', nameAr: 'أرمينيا', currency: 'AMD' },
  { code: 'AU', name: 'Australia', nameAr: 'أستراليا', currency: 'AUD' },
  { code: 'AT', name: 'Austria', nameAr: 'النمسا', currency: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', nameAr: 'أذربيجان', currency: 'AZN' },
  { code: 'BS', name: 'Bahrain', nameAr: 'البحرين', currency: 'BHD' },
  { code: 'BD', name: 'Bangladesh', nameAr: 'بنغلاديش', currency: 'BDT' },
  { code: 'BY', name: 'Belarus', nameAr: 'بيلاروسيا', currency: 'BYN' },
  { code: 'BE', name: 'Belgium', nameAr: 'بلجيكا', currency: 'EUR' },
  { code: 'BO', name: 'Bolivia', nameAr: 'بوليفيا', currency: 'BOB' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', currency: 'BAM' },
  { code: 'BR', name: 'Brazil', nameAr: 'البرازيل', currency: 'BRL' },
  { code: 'BG', name: 'Bulgaria', nameAr: 'بلغاريا', currency: 'BGN' },
  { code: 'KH', name: 'Cambodia', nameAr: 'كمبوديا', currency: 'KHR' },
  { code: 'CM', name: 'Cameroon', nameAr: 'الكاميرون', currency: 'XAF' },
  { code: 'CA', name: 'Canada', nameAr: 'كندا', currency: 'CAD' },
  { code: 'CL', name: 'Chile', nameAr: 'تشيلي', currency: 'CLP' },
  { code: 'CN', name: 'China', nameAr: 'الصين', currency: 'CNY' },
  { code: 'CO', name: 'Colombia', nameAr: 'كولومبيا', currency: 'COP' },
  { code: 'CR', name: 'Costa Rica', nameAr: 'كوستاريكا', currency: 'CRC' },
  { code: 'HR', name: 'Croatia', nameAr: 'كرواتيا', currency: 'HRK' },
  { code: 'CU', name: 'Cuba', nameAr: 'كوبا', currency: 'CUP' },
  { code: 'CY', name: 'Cyprus', nameAr: 'قبرص', currency: 'EUR' },
  { code: 'CZ', name: 'Czech Republic', nameAr: 'التشيك', currency: 'CZK' },
  { code: 'DK', name: 'Denmark', nameAr: 'الدنمارك', currency: 'DKK' },
  { code: 'DO', name: 'Dominican Republic', nameAr: 'الدومينيكان', currency: 'DOP' },
  { code: 'EC', name: 'Ecuador', nameAr: 'الإكوادور', currency: 'USD' },
  { code: 'EG', name: 'Egypt', nameAr: 'مصر', currency: 'EGP' },
  { code: 'SV', name: 'El Salvador', nameAr: 'السلفادور', currency: 'USD' },
  { code: 'EE', name: 'Estonia', nameAr: 'إستونيا', currency: 'EUR' },
  { code: 'ET', name: 'Ethiopia', nameAr: 'إثيوبيا', currency: 'ETB' },
  { code: 'FI', name: 'Finland', nameAr: 'فنلندا', currency: 'EUR' },
  { code: 'FR', name: 'France', nameAr: 'فرنسا', currency: 'EUR' },
  { code: 'GE', name: 'Georgia', nameAr: 'جورجيا', currency: 'GEL' },
  { code: 'DE', name: 'Germany', nameAr: 'ألمانيا', currency: 'EUR' },
  { code: 'GH', name: 'Ghana', nameAr: 'غانا', currency: 'GHS' },
  { code: 'GR', name: 'Greece', nameAr: 'اليونان', currency: 'EUR' },
  { code: 'GT', name: 'Guatemala', nameAr: 'غواتيمالا', currency: 'GTQ' },
  { code: 'HN', name: 'Honduras', nameAr: 'هندوراس', currency: 'HNL' },
  { code: 'HK', name: 'Hong Kong', nameAr: 'هونغ كونغ', currency: 'HKD' },
  { code: 'HU', name: 'Hungary', nameAr: 'المجر', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', nameAr: 'آيسلندا', currency: 'ISK' },
  { code: 'IN', name: 'India', nameAr: 'الهند', currency: 'INR' },
  { code: 'ID', name: 'Indonesia', nameAr: 'إندونيسيا', currency: 'IDR' },
  { code: 'IR', name: 'Iran', nameAr: 'إيران', currency: 'IRR' },
  { code: 'IQ', name: 'Iraq', nameAr: 'العراق', currency: 'IQD' },
  { code: 'IE', name: 'Ireland', nameAr: 'أيرلندا', currency: 'EUR' },
  { code: 'IL', name: 'Israel', nameAr: 'إسرائيل', currency: 'ILS' },
  { code: 'IT', name: 'Italy', nameAr: 'إيطاليا', currency: 'EUR' },
  { code: 'JM', name: 'Jamaica', nameAr: 'جامايكا', currency: 'JMD' },
  { code: 'JP', name: 'Japan', nameAr: 'اليابان', currency: 'JPY' },
  { code: 'JO', name: 'Jordan', nameAr: 'الأردن', currency: 'JOD' },
  { code: 'KZ', name: 'Kazakhstan', nameAr: 'كازاخستان', currency: 'KZT' },
  { code: 'KE', name: 'Kenya', nameAr: 'كينيا', currency: 'KES' },
  { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', currency: 'KWD' },
  { code: 'LB', name: 'Lebanon', nameAr: 'لبنان', currency: 'LBP' },
  { code: 'LY', name: 'Libya', nameAr: 'ليبيا', currency: 'LYD' },
  { code: 'MY', name: 'Malaysia', nameAr: 'ماليزيا', currency: 'MYR' },
  { code: 'MX', name: 'Mexico', nameAr: 'المكسيك', currency: 'MXN' },
  { code: 'MA', name: 'Morocco', nameAr: 'المغرب', currency: 'MAD' },
  { code: 'NL', name: 'Netherlands', nameAr: 'هولندا', currency: 'EUR' },
  { code: 'NZ', name: 'New Zealand', nameAr: 'نيوزيلندا', currency: 'NZD' },
  { code: 'NG', name: 'Nigeria', nameAr: 'نيجيريا', currency: 'NGN' },
  { code: 'NO', name: 'Norway', nameAr: 'النرويج', currency: 'NOK' },
  { code: 'OM', name: 'Oman', nameAr: 'عُمان', currency: 'OMR' },
  { code: 'PK', name: 'Pakistan', nameAr: 'باكستان', currency: 'PKR' },
  { code: 'PS', name: 'Palestine', nameAr: 'فلسطين', currency: 'ILS' },
  { code: 'PA', name: 'Panama', nameAr: 'بنما', currency: 'PAB' },
  { code: 'PY', name: 'Paraguay', nameAr: 'باراغواي', currency: 'PYG' },
  { code: 'PE', name: 'Peru', nameAr: 'بيرو', currency: 'PEN' },
  { code: 'PH', name: 'Philippines', nameAr: 'الفلبين', currency: 'PHP' },
  { code: 'PL', name: 'Poland', nameAr: 'بولندا', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', nameAr: 'البرتغال', currency: 'EUR' },
  { code: 'QA', name: 'Qatar', nameAr: 'قطر', currency: 'QAR' },
  { code: 'RO', name: 'Romania', nameAr: 'رومانيا', currency: 'RON' },
  { code: 'RU', name: 'Russia', nameAr: 'روسيا', currency: 'RUB' },
  { code: 'SA', name: 'Saudi Arabia', nameAr: 'السعودية', currency: 'SAR' },
  { code: 'RS', name: 'Serbia', nameAr: 'صربيا', currency: 'RSD' },
  { code: 'SG', name: 'Singapore', nameAr: 'سنغافورة', currency: 'SGD' },
  { code: 'ZA', name: 'South Africa', nameAr: 'جنوب أفريقيا', currency: 'ZAR' },
  { code: 'KR', name: 'South Korea', nameAr: 'كوريا الجنوبية', currency: 'KRW' },
  { code: 'ES', name: 'Spain', nameAr: 'إسبانيا', currency: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', nameAr: 'سريلانكا', currency: 'LKR' },
  { code: 'SD', name: 'Sudan', nameAr: 'السودان', currency: 'SDG' },
  { code: 'SE', name: 'Sweden', nameAr: 'السويد', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', nameAr: 'سويسرا', currency: 'CHF' },
  { code: 'SY', name: 'Syria', nameAr: 'سوريا', currency: 'SYP' },
  { code: 'TW', name: 'Taiwan', nameAr: 'تايوان', currency: 'TWD' },
  { code: 'TH', name: 'Thailand', nameAr: 'تايلاند', currency: 'THB' },
  { code: 'TN', name: 'Tunisia', nameAr: 'تونس', currency: 'TND' },
  { code: 'TR', name: 'Turkey', nameAr: 'تركيا', currency: 'TRY' },
  { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', currency: '£' },
  { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', currency: '$' },
  { code: 'UY', name: 'Uruguay', nameAr: 'أوروغواي', currency: 'UYU' },
  { code: 'VE', name: 'Venezuela', nameAr: 'فنزويلا', currency: 'VES' },
  { code: 'VN', name: 'Vietnam', nameAr: 'فيتنام', currency: 'VND' },
  { code: 'YE', name: 'Yemen', nameAr: 'اليمن', currency: 'YER' },
];

export const getCurrencySymbol = (code: string) => {
  const map: Record<string, string> = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'SAR': 'SAR',
    'AED': 'AED',
    'EGP': 'EGP',
    'KWD': 'KWD',
    'QAR': 'QAR',
    'OMR': 'OMR',
    'BHD': 'BHD',
    'JOD': 'JOD',
    'JPY': '¥',
    'CNY': '¥',
    'INR': '₹',
    'RUB': '₽',
    'KRW': '₩',
    'TRY': '₺',
    'BRL': 'R$',
  };
  return map[code] || code;
};
