/**
 * Currency options offered in Restaurant Info.
 * Extracted from the inline <option> list so the form stays readable.
 */
export const CURRENCIES: { code: string; label: string }[] = [
  { code: '$', label: '$ (USD)' },
  { code: '€', label: '€ (EUR)' },
  { code: '£', label: '£ (GBP)' },
  { code: 'SAR', label: 'SAR (Saudi Riyal)' },
  { code: 'AED', label: 'AED (UAE Dirham)' },
  { code: 'EGP', label: 'EGP (Egyptian Pound)' },
  { code: 'KWD', label: 'KWD (Kuwaiti Dinar)' },
  { code: 'QAR', label: 'QAR (Qatari Dinar)' },
  { code: 'OMR', label: 'OMR (Omani Rial)' },
  { code: 'BHD', label: 'BHD (Bahraini Dinar)' },
  { code: 'JOD', label: 'JOD (Jordanian Dinar)' },
  { code: 'AFN', label: 'AFN (Afghan Afghani)' },
  { code: 'ALL', label: 'ALL (Albanian Lek)' },
  { code: 'DZD', label: 'DZD (Algerian Dinar)' },
  { code: 'AOA', label: 'AOA (Angolan Kwanza)' },
  { code: 'ARS', label: 'ARS (Argentine Peso)' },
  { code: 'AMD', label: 'AMD (Armenian Dram)' },
  { code: 'AUD', label: 'AUD (Australian Dollar)' },
  { code: 'AZN', label: 'AZN (Azerbaijani Manat)' },
  { code: 'BDT', label: 'BDT (Bangladeshi Taka)' },
  { code: 'BYN', label: 'BYN (Belarusian Ruble)' },
  { code: 'BOB', label: 'BOB (Bolivian Boliviano)' },
  { code: 'BAM', label: 'BAM (Bosnia-Herzegovina Convertible Mark)' },
  { code: 'BRL', label: 'BRL (Brazilian Real)' },
  { code: 'BGN', label: 'BGN (Bulgarian Lev)' },
  { code: 'KHR', label: 'KHR (Cambodian Riel)' },
  { code: 'XAF', label: 'XAF (Central African CFA Franc)' },
  { code: 'CAD', label: 'CAD (Canadian Dollar)' },
  { code: 'CLP', label: 'CLP (Chilean Peso)' },
  { code: 'CNY', label: 'CNY (Chinese Yuan)' },
  { code: 'COP', label: 'COP (Colombian Peso)' },
  { code: 'CRC', label: 'CRC (Costa Rican Colón)' },
  { code: 'HRK', label: 'HRK (Croatian Kuna)' },
  { code: 'CUP', label: 'CUP (Cuban Peso)' },
  { code: 'CZK', label: 'CZK (Czech Koruna)' },
  { code: 'DKK', label: 'DKK (Danish Krone)' },
  { code: 'DOP', label: 'DOP (Dominican Peso)' },
  { code: 'ETB', label: 'ETB (Ethiopian Birr)' },
  { code: 'GEL', label: 'GEL (Georgian Lari)' },
  { code: 'GHS', label: 'GHS (Ghanaian Cedi)' },
  { code: 'GTQ', label: 'GTQ (Guatemalan Quetzal)' },
  { code: 'HNL', label: 'HNL (Honduran Lempira)' },
  { code: 'HKD', label: 'HKD (Hong Kong Dollar)' },
  { code: 'HUF', label: 'HUF (Hungarian Forint)' },
  { code: 'ISK', label: 'ISK (Icelandic Króna)' },
  { code: 'INR', label: 'INR (Indian Rupee)' },
  { code: 'IDR', label: 'IDR (Indonesian Rupiah)' },
  { code: 'IRR', label: 'IRR (Iranian Rial)' },
  { code: 'IQD', label: 'IQD (Iraqi Dinar)' },
  { code: 'ILS', label: 'ILS (Israeli New Shekel)' },
  { code: 'JMD', label: 'JMD (Jamaican Dollar)' },
  { code: 'JPY', label: 'JPY (Japanese Yen)' },
  { code: 'KZT', label: 'KZT (Kazakhstani Tenge)' },
  { code: 'KES', label: 'KES (Kenyan Shilling)' },
  { code: 'LBP', label: 'LBP (Lebanese Pound)' },
  { code: 'LYD', label: 'LYD (Libyan Dinar)' },
  { code: 'MYR', label: 'MYR (Malaysian Ringgit)' },
  { code: 'MXN', label: 'MXN (Mexican Peso)' },
  { code: 'MAD', label: 'MAD (Moroccan Dirham)' },
  { code: 'NZD', label: 'NZD (New Zealand Dollar)' },
  { code: 'NGN', label: 'NGN (Nigerian Naira)' },
  { code: 'NOK', label: 'NOK (Norwegian Krone)' },
  { code: 'PKR', label: 'PKR (Pakistani Rupee)' },
  { code: 'PAB', label: 'PAB (Panamanian Balboa)' },
  { code: 'PYG', label: 'PYG (Paraguayan Guaraní)' },
  { code: 'PEN', label: 'PEN (Peruvian Sol)' },
  { code: 'PHP', label: 'PHP (Philippine Peso)' },
  { code: 'PLN', label: 'PLN (Polish Złoty)' },
  { code: 'RON', label: 'RON (Romanian Leu)' },
  { code: 'RUB', label: 'RUB (Russian Ruble)' },
  { code: 'RSD', label: 'RSD (Serbian Dinar)' },
  { code: 'SGD', label: 'SGD (Singapore Dollar)' },
  { code: 'ZAR', label: 'ZAR (South African Rand)' },
  { code: 'KRW', label: 'KRW (South Korean Won)' },
  { code: 'LKR', label: 'LKR (Sri Lankan Rupee)' },
  { code: 'SDG', label: 'SDG (Sudanese Pound)' },
  { code: 'SEK', label: 'SEK (Swedish Krona)' },
  { code: 'CHF', label: 'CHF (Swiss Franc)' },
  { code: 'SYP', label: 'SYP (Syrian Pound)' },
  { code: 'TWD', label: 'TWD (New Taiwan Dollar)' },
  { code: 'THB', label: 'THB (Thai Baht)' },
  { code: 'TND', label: 'TND (Tunisian Dinar)' },
  { code: 'TRY', label: 'TRY (Turkish Lira)' },
  { code: 'UYU', label: 'UYU (Uruguayan Peso)' },
  { code: 'VES', label: 'VES (Venezuelan Bolívar)' },
  { code: 'VND', label: 'VND (Vietnamese Đồng)' },
  { code: 'YER', label: 'YER (Yemeni Rial)' },
];
